[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "rvfl"
version = "0.0.0"
description = "RVFL baseline and variants"
requires-python = ">=3.12"
dependencies = ["numpy", "scikit-learn", "pandas"]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
rvfl = ["testdata/**/*"]

[project.optional-dependencies]
test = [
    "ucimlrepo",
    "pytest",
    "pytest-cov",
]
