[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "rvfl"
version = "0.0.0"
description = "RVFL baseline and variants"
requires-python = ">=3.12"
dependencies = ["numpy", "scikit-learn", "pandas"]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
rvfl = ["testdata/**/*"]


[project.optional-dependencies]
test = [
    "ucimlrepo",
    "pytest",
    "pytest-cov",

[tool.numpydoc_validation]
checks = [
    "all", # report on all checks, except the below
    "EX01", # we don't require examples sections yet
    "SA01", # we don't require "See Also" sections
    "ES01", # we don't require extended summaries
]

exclude = [
    '\.__init__$',
    '\._check_voting$',
    '\._forward$',
    'EnsembleRVFL(\.|$)', # ignore base class
    'RVFL(\.|$)', # ignore base class
]
